// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAetLlBQcyS5WlAmbg3fvEBRhgDQw11uPI',
    appId: '1:234567568334:web:ffc452620edd8204eaf99f',
    messagingSenderId: '234567568334',
    projectId: 'nk-app-693ab',
    authDomain: 'nk-app-693ab.firebaseapp.com',
    storageBucket: 'nk-app-693ab.appspot.com',
    measurementId: 'G-8FQ9Y0LEHQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtjHjSUg2pDwHYGnzuQ1jQsIAAi1ZAI0Y',
    appId: '1:234567568334:android:eccf72ae7cf84734eaf99f',
    messagingSenderId: '234567568334',
    projectId: 'nk-app-693ab',
    storageBucket: 'nk-app-693ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADGozYWxZUKAvlyCzTBHceJcnLw1Y9wCk',
    appId: '1:234567568334:ios:123931cefdd6d60aeaf99f',
    messagingSenderId: '234567568334',
    projectId: 'nk-app-693ab',
    storageBucket: 'nk-app-693ab.appspot.com',
    iosBundleId: 'com.example.chatappFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADGozYWxZUKAvlyCzTBHceJcnLw1Y9wCk',
    appId: '1:234567568334:ios:123931cefdd6d60aeaf99f',
    messagingSenderId: '234567568334',
    projectId: 'nk-app-693ab',
    storageBucket: 'nk-app-693ab.appspot.com',
    iosBundleId: 'com.example.chatappFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAetLlBQcyS5WlAmbg3fvEBRhgDQw11uPI',
    appId: '1:234567568334:web:fe91138ff613aff7eaf99f',
    messagingSenderId: '234567568334',
    projectId: 'nk-app-693ab',
    authDomain: 'nk-app-693ab.firebaseapp.com',
    storageBucket: 'nk-app-693ab.appspot.com',
    measurementId: 'G-8K9KN96T4B',
  );

}