// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY3Zq7sMasAkWaeiqj_A7zgnW9VSLSnvM',
    appId: '1:342323123797:web:5192cb2d65c91c75cde6dc',
    messagingSenderId: '342323123797',
    projectId: 'chatapp-2ab0a',
    authDomain: 'chatapp-2ab0a.firebaseapp.com',
    storageBucket: 'chatapp-2ab0a.appspot.com',
    measurementId: 'G-9L3EK37211',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl0bzSD1WR8A6QIokBht1BxjANfA3deh0',
    appId: '1:342323123797:android:6943a17b8f73e8a7cde6dc',
    messagingSenderId: '342323123797',
    projectId: 'chatapp-2ab0a',
    storageBucket: 'chatapp-2ab0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAktku9IGzkxPF6Ndcfmsm8OsmtcDx7vnA',
    appId: '1:342323123797:ios:453a90fc8e78b9a2cde6dc',
    messagingSenderId: '342323123797',
    projectId: 'chatapp-2ab0a',
    storageBucket: 'chatapp-2ab0a.appspot.com',
    iosBundleId: 'com.example.chatappFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAktku9IGzkxPF6Ndcfmsm8OsmtcDx7vnA',
    appId: '1:342323123797:ios:453a90fc8e78b9a2cde6dc',
    messagingSenderId: '342323123797',
    projectId: 'chatapp-2ab0a',
    storageBucket: 'chatapp-2ab0a.appspot.com',
    iosBundleId: 'com.example.chatappFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDY3Zq7sMasAkWaeiqj_A7zgnW9VSLSnvM',
    appId: '1:342323123797:web:8fec2f659e7619f6cde6dc',
    messagingSenderId: '342323123797',
    projectId: 'chatapp-2ab0a',
    authDomain: 'chatapp-2ab0a.firebaseapp.com',
    storageBucket: 'chatapp-2ab0a.appspot.com',
    measurementId: 'G-YR33NWQQ58',
  );
}
